name: Publish resume as Github Page

# Controls when the action will run.
on:
    push:
        branches:
            - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - uses: actions/setup-node@v5
              with:
                node-version: 18
            
            - name: Install Node dependencies
              run: npm install

            - name: Build resume HTML for Github Pages
              run: npx resume export build/index.html --resume resume.en.json --format html --theme jsonresume-theme-relaxed

            - name: Build resume (fr) PDF for Github Pages
              run: npx resume export build/quentin_dequippe_resume.pdf --resume resume.fr.json --format pdf --theme jsonresume-theme-relaxed

            - name: Build resume (en) PDF for Github Pages
              run: npx resume export build/quentin_dequippe_resume.en.pdf --resume resume.en.json --format pdf --theme jsonresume-theme-relaxed

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                path: ./build

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
